import env from '../../config/env';

const getAllDictionaryByClazzFunc = () => {
  return {
    status: 200,
    message: '数据获取成功',
    data: {
      Dict: [
        {
          id: 38,
          industryName: '交通物流',
        },
        {
          id: 39,
          industryName: '教育',
        },
        {
          id: 40,
          industryName: '文旅',
        },
        {
          id: 41,
          industryName: '新媒体',
        },
        {
          id: 42,
          industryName: '生态环境',
        },
        {
          id: 43,
          industryName: '金融银行',
        },
        {
          id: 44,
          industryName: '医疗健康',
        },
        {
          id: 45,
          industryName: '冬奥',
        },
        {
          id: 46,
          industryName: '工业互联网',
        },
        {
          id: 47,
          industryName: '能源',
        },
        {
          id: 48,
          industryName: '智慧城市',
        },
        {
          id: 49,
          industryName: '数字政府',
        },
        {
          id: 50,
          industryName: '其他',
        },
      ],
    },
    succeed: true,
  };
};

const fetchRecommendationsPage = () => {
  return {
    status: 200,
    message: null,
    data: {
      totalElements: 39,
      totalPages: 5,
      content: [
        {
          id: 850,
          clazz: 'warehouse',
          title: 'CV测试测试',
          content: null,
          shortTitle: null,
          brief:
            '<p>工具人工具人</p><p>工具人工具人</p><p>工具人工具人</p><p>工具人工具人</p><p>工具人工具人</p>',
          icon:
            '/image/202012/1607413943381/%E6%B3%A1%E8%8A%99.jpg?Expires=1607527716&OSSAccessKeyId=ezFM9xmuC2GGA4Zm&Signature=0NQ498m6qBFm%2BVQWpFMPap9pdOs%3D',
          propagandaImage: null,
          recommendation: 0,
          showH5: 0,
          h5Url: null,
          creator: null,
          status: '3',
          updateTime: 1607413944000,
          createTime: 1607413944000,
          ranged: 0,
          createTimeStr: '20201208155224',
          updateTimeStr: '20201208155224',
          startTimeStr: null,
          endTimeStr: null,
          scenario: null,
          worth: null,
          industryId: 40,
          stpartyCode: null,
          ecosphere: null,
          contacts: '工具人',
          telephone: '1231312',
          provinceName: null,
          provinceCode: '99',
          cityName: null,
          cityCode: null,
          taskId: null,
          companyName: null,
          imageList: null,
          industryName: '文旅',
          fileList: null,
        },
        {
          id: 849,
          clazz: 'warehouse',
          title: 'cv测试2',
          content: null,
          shortTitle: null,
          brief:
            '<p>工具人</p><p>工具人</p><p>工具人<br/>工具人<br/>工具人<br/>工具人<br/>工具人<br/>工具人<br/>工具人<br/>工具人</p>',
          icon:
            '/image/202012/1607413777294/%E6%B3%A1%E8%8A%99.jpg?Expires=1607527716&OSSAccessKeyId=ezFM9xmuC2GGA4Zm&Signature=J39%2B9gd5vgHQeLN9tntJUZsT%2FEU%3D',
          propagandaImage: null,
          recommendation: 0,
          showH5: 0,
          h5Url: null,
          creator: null,
          status: '3',
          updateTime: 1607413778000,
          createTime: 1607413778000,
          ranged: 0,
          createTimeStr: '20201208154938',
          updateTimeStr: '20201208154938',
          startTimeStr: null,
          endTimeStr: null,
          scenario: null,
          worth: null,
          industryId: 39,
          stpartyCode: null,
          ecosphere: null,
          contacts: '工具人',
          telephone: '22223333',
          provinceName: null,
          provinceCode: '99',
          cityName: null,
          cityCode: null,
          taskId: null,
          companyName: null,
          imageList: null,
          industryName: '教育',
          fileList: null,
        },
        {
          id: 837,
          clazz: 'warehouse',
          title: 'test112411',
          content: null,
          shortTitle: null,
          brief: '<p>test112411</p>',
          icon: null,
          propagandaImage: null,
          recommendation: 0,
          showH5: 0,
          h5Url: null,
          creator: null,
          status: '3',
          updateTime: 1606211669000,
          createTime: 1606211669000,
          ranged: 0,
          createTimeStr: '20201124175429',
          updateTimeStr: '20201124175429',
          startTimeStr: null,
          endTimeStr: null,
          scenario: null,
          worth: null,
          industryId: 39,
          stpartyCode: null,
          ecosphere: null,
          contacts: 'test112411',
          telephone: '2563263',
          provinceName: null,
          provinceCode: '18',
          cityName: null,
          cityCode: '182',
          taskId: null,
          companyName: null,
          imageList: null,
          industryName: '教育',
          fileList: null,
        },
        {
          id: 833,
          clazz: 'warehouse',
          title: '测试服2',
          content: null,
          shortTitle: null,
          brief: '<p>测试服2</p>',
          icon: null,
          propagandaImage: null,
          recommendation: 0,
          showH5: 0,
          h5Url: null,
          creator: null,
          status: '3',
          updateTime: 1606143105000,
          createTime: 1606143105000,
          ranged: 0,
          createTimeStr: '20201123225145',
          updateTimeStr: '20201123225145',
          startTimeStr: null,
          endTimeStr: null,
          scenario: null,
          worth: null,
          industryId: 40,
          stpartyCode: null,
          ecosphere: null,
          contacts: '测试服2',
          telephone: '78988909',
          provinceName: null,
          provinceCode: '13',
          cityName: null,
          cityCode: null,
          taskId: null,
          companyName: null,
          imageList: null,
          industryName: '文旅',
          fileList: null,
        },
        {
          id: 832,
          clazz: 'warehouse',
          title: '测试服1',
          content: null,
          shortTitle: null,
          brief: '<p>测试服1</p>',
          icon: null,
          propagandaImage: null,
          recommendation: 0,
          showH5: 0,
          h5Url: null,
          creator: null,
          status: '3',
          updateTime: 1606135787000,
          createTime: 1606135787000,
          ranged: 0,
          createTimeStr: '20201123204947',
          updateTimeStr: '20201123204947',
          startTimeStr: null,
          endTimeStr: null,
          scenario: null,
          worth: null,
          industryId: 40,
          stpartyCode: null,
          ecosphere: null,
          contacts: '测试服1',
          telephone: '67878989',
          provinceName: null,
          provinceCode: '13',
          cityName: null,
          cityCode: null,
          taskId: null,
          companyName: null,
          imageList: null,
          industryName: '文旅',
          fileList: null,
        },
        {
          id: 831,
          clazz: 'warehouse',
          title: '测试服',
          content: null,
          shortTitle: null,
          brief: '<p>测试服</p>',
          icon: null,
          propagandaImage: null,
          recommendation: 0,
          showH5: 0,
          h5Url: null,
          creator: null,
          status: '3',
          updateTime: 1606133136000,
          createTime: 1606133136000,
          ranged: 0,
          createTimeStr: '20201123200536',
          updateTimeStr: '20201123200536',
          startTimeStr: null,
          endTimeStr: null,
          scenario: null,
          worth: null,
          industryId: 40,
          stpartyCode: null,
          ecosphere: null,
          contacts: '测试服',
          telephone: '12346789',
          provinceName: null,
          provinceCode: '11',
          cityName: null,
          cityCode: null,
          taskId: null,
          companyName: null,
          imageList: null,
          industryName: '文旅',
          fileList: null,
        },
        {
          id: 830,
          clazz: 'warehouse',
          title: '测试测试测试三',
          content: null,
          shortTitle: null,
          brief: '<p>测试测试测试三</p>',
          icon: null,
          propagandaImage: null,
          recommendation: 0,
          showH5: 0,
          h5Url: null,
          creator: null,
          status: '3',
          updateTime: 1606130762000,
          createTime: 1606130762000,
          ranged: 0,
          createTimeStr: '20201123192602',
          updateTimeStr: '20201123192602',
          startTimeStr: null,
          endTimeStr: null,
          scenario: null,
          worth: null,
          industryId: 40,
          stpartyCode: null,
          ecosphere: null,
          contacts: '测试',
          telephone: '12222222',
          provinceName: null,
          provinceCode: '13',
          cityName: null,
          cityCode: null,
          taskId: null,
          companyName: null,
          imageList: null,
          industryName: '文旅',
          fileList: null,
        },
        {
          id: 827,
          clazz: 'warehouse',
          title: '1qwe22',
          content: null,
          shortTitle: null,
          brief: '<p>qqqq</p>',
          icon: null,
          propagandaImage: null,
          recommendation: 0,
          showH5: 0,
          h5Url: null,
          creator: null,
          status: '3',
          updateTime: 1606121648000,
          createTime: 1606121648000,
          ranged: 0,
          createTimeStr: '20201123165408',
          updateTimeStr: '20201123165408',
          startTimeStr: null,
          endTimeStr: null,
          scenario: null,
          worth: null,
          industryId: 39,
          stpartyCode: null,
          ecosphere: null,
          contacts: 'qas',
          telephone: '13425676654',
          provinceName: null,
          provinceCode: '99',
          cityName: null,
          cityCode: null,
          taskId: null,
          companyName: null,
          imageList: null,
          industryName: '教育',
          fileList: null,
        },
        {
          id: 812,
          clazz: 'warehouse',
          title: '工具人13',
          content: null,
          shortTitle: null,
          brief: '工具人',
          icon: null,
          propagandaImage: null,
          recommendation: 0,
          showH5: 0,
          h5Url: null,
          creator: null,
          status: '3',
          updateTime: 1606027941000,
          createTime: 1606027941000,
          ranged: 0,
          createTimeStr: '20201122145221',
          updateTimeStr: '20201122145221',
          startTimeStr: null,
          endTimeStr: null,
          scenario: null,
          worth: null,
          industryId: 48,
          stpartyCode: null,
          ecosphere: 0,
          contacts: '工具人',
          telephone: '18620020000',
          provinceName: null,
          provinceCode: '51',
          cityName: null,
          cityCode: null,
          taskId: null,
          companyName: null,
          imageList: null,
          industryName: '智慧城市',
          fileList: null,
        },
      ],
    },
    succeed: true,
  };
};

const fetAppStorageDetail = () => {
  return {
    status: 200,
    message: null,
    data: {
      id: 849,
      clazz: 'warehouse',
      title: 'cv测试2',
      content: null,
      shortTitle: null,
      brief:
        '<p>工具人</p><p>工具人</p><p>工具人<br/>工具人<br/>工具人<br/>工具人<br/>工具人<br/>工具人<br/>工具人<br/>工具人</p>',
      icon: null,
      propagandaImage: null,
      recommendation: 1,
      showH5: 0,
      h5Url: null,
      creator: 101679,
      status: '3',
      updateTime: 1607413778000,
      createTime: 1607413778000,
      ranged: 0,
      createTimeStr: '20201208154938',
      updateTimeStr: '20201208154938',
      startTimeStr: null,
      endTimeStr: null,
      scenario:
        '<p>工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人</p>',
      worth:
        '<p>工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人工具人</p>',
      industryId: 39,
      stpartyCode: 22007240000,
      ecosphere: null,
      contacts: '',
      telephone: '',
      provinceName: '全国',
      provinceCode: '99',
      cityName: null,
      cityCode: null,
      taskId: '',
      companyName: null,
      imageList: [
        '/image/202012/1607413777294/%E6%B3%A1%E8%8A%99.jpg?Expires=1607528164&OSSAccessKeyId=ezFM9xmuC2GGA4Zm&Signature=F9yyPjtkyPN8b%2BZOfwPscH%2FKgII%3D',
      ],
      industryName: '教育',
      fileList: [
        {
          uid: 931,
          url:
            '/partners/image/202012/1607413777294/%E6%B3%A1%E8%8A%99.jpg?Expires=1607528164&OSSAccessKeyId=ezFM9xmuC2GGA4Zm&Signature=F9yyPjtkyPN8b%2BZOfwPscH%2FKgII%3D',
        },
      ],
      praiseStatus: 0,
      countPraise: 0,
      countBrowse: 0,
    },
    succeed: true,
  };
};

export default {
  [`GET ${env.baseUrl}/cu5gaia/lib/warehouse/getAllDictionaryByClazz`]: getAllDictionaryByClazzFunc(),
  [`GET ${env.baseUrl}/cu5gaia/lib/warehouse/recommendations/page`]: fetchRecommendationsPage(),
  [`GET ${env.baseUrl}/cu5gaia/lib/warehouse/detail`]: fetAppStorageDetail(),
};
